### ISSUE TITLE
What is returned by solve?

### ISSUE THREAD

**Issue by KOLANICH** [pablormier/yabox#34]
https://github.com/pablormier/yabox/blob/master/yabox/algorithms/de.py#L192

Why not to return `P[idx]`?

**Comment by gasilva** [comment]
Yes I have a vector with 11 parameters as an answer. What is the minimum?

**Comment by pablormier** [comment]
I uploaded a new notebook with an example of how to monitor and get the optimal  value and error in an iterative fashion. Cheeck the yabox-tutorial.ipynb
