### ISSUE TITLE
pass variable parameters

### ISSUE THREAD

**Issue by gasilva** [pablormier/yabox#38]
The code below only applies when you have constant parameters.
They are defined inside the function. No problem. 

```
def fun(x, a, b):
    return a + sum(x**2) / (b + 1)

def f(x):
    # You can initialize here your params a, b
    return fun(x, 10, -2)

DE(f, [(-10, 10)], maxiters=1000).solve(show_progress=True)
```

But I have variable parameters. It varies according to the country to define the ODE for COVID-19 infection rate, death rate and recovered rates.

[https://github.com/gasilva/dataAndModelsCovid19](https://github.com/gasilva/dataAndModelsCovid19)

So I need to pass the parameters at the begining of the run. They are the initial conditions for ODE solver and some other control parameters.

**Comment by pablormier** [comment]
You can still do that:

```python
def create_loss_function(initial_conditions):
  # Do whatever you need to do here
  def fun(x):
    return x*initial_conditions[1] + x**2 * initial_conditions[2] ... #whatever function
  return fun

f = create_loss_function(your_initial_conditions)
DE(f, [(-10, 10)], maxiters=1000).solve(show_progress=True)
```

Cheers

**Comment by gasilva** [comment]
what is the returned value of create_loss_function?
how the first (nested) returned in passed?
the code is saying that function create_loss_function has None value. @pablormier

**Comment by gasilva** [comment]
This is the function I created with your tips but it is still not working

```
def create_lossOdeint(data, recovered, \
            death, s_0, e_0, a_0, i_0, r_0, d_0, startNCases, \
                 weigthCases, weigthRecov):
    def lossOdeint(point):
        size = len(data)
        beta, beta2, sigma, sigma2, sigma3, gamma, b, mu = point
        def SEAIRD(y,t):
            S = y[0]
            E = y[1]
            A = y[2]
            I = y[3]
            R = y[4]
            p=0.2
            # beta2=beta
            y0=-(beta2*A+beta*I)*S+mu*S #S
            y1=(beta2*A+beta*I)*S-sigma*E-mu*E #E
            y2=sigma*E*(1-p)-gamma*A-mu*A #A
            y3=sigma*E*p-gamma*I-sigma2*I-sigma3*I-mu*I #I
            y4=b*I+gamma*A+sigma2*I-mu*R #R
            y5=(-(y0+y1+y2+y3+y4)) #D
            return [y0,y1,y2,y3,y4,y5]

        y0=[s_0,e_0,a_0,i_0,r_0,d_0]
        tspan=np.arange(0, size, 1)
        res=odeint(SEAIRD,y0,tspan) 
        #,hmax=0.01)

        tot=0
        l1=0
        l2=0
        l3=0
        for i in range(0,len(data.values)):
            if data.values[i]>startNCases:
                l1 = l1+(res[i,3] - data.values[i])**2
                l2 = l2+(res[i,5] - death.values[i])**2
                l3 = l3+(res[i,4] - recovered.values[i])**2
                tot+=1
        l1=np.sqrt(l1/max(1,tot))
        l2=np.sqrt(l2/max(1,tot))
        l3=np.sqrt(l3/max(1,tot))
        
        #weight for cases
        u = weigthCases
        #weight for recovered
        w = weigthRecov 
        #weight for deaths
        v = max(0,1. - u - w)
        return u*l1 + v*l2 + w*l3
```

the value to be minimized is `u*l1 + v*l2 + w*l3`

the `point` is the `x` array. 

the `data, recovered, death, s_0, e_0, a_0, i_0, r_0, d_0, startNCases, weigthCases, weigthRecov `are the parameters

**Comment by pablormier** [comment]
You have to return the function at the end:
`return lossOdeint`

The idea is that you return a function to pass to the minimizer. So if you do
`f = create_lossOdeint(data, recovered, death, s_0, e_0, a_0, i_0, r_0, d_0, startNCases, weigthCases, weigthRecov)`
Then you can call it
`loss_value = f(x)`

Basically, you are wrapping the initial conditions and you are returning a function with those arguments fixed, so you can evaluate it just on the x values and you don't need to provide the initial conditions any more.

Hope it helps

**Comment by gasilva** [comment]
Yes. It worked! Many thanks.

Guilherme A. Lima da Silva
http://www.ats4i.com/


Em seg., 11 de mai. de 2020 às 15:17, Pablo R. Mier <
notifications@github.com> escreveu:
