### ISSUE TITLE
Typo in de.py 

### ISSUE THREAD

**Issue by cypark0411** [pablormier/yabox#41]
Your codes are very helpful to solve my projects.

While I applied your code, I found a typo that you might know already.

Typo part:
    de.py -> class DE -> def solve

'return' might be changed as follows:

Original code: 
    return  self.denormalize(P[idx].reshape(-1, 1)), fitness[idx]

Fixed:
    return  self.denormalize(P[idx].reshape(1, -1)), fitness[idx]

**Comment by pablormier** [comment]
Fixed in v1.1.0. Thanks!
